// journeys/example.spec.js
//
// A Playwright `codegen`-style journey that mirrors journeys/example.yaml
// (Branch Magazine reader). Generated by `npx playwright codegen
// https://branch.climateaction.tech` and lightly hand-edited.
//
// Run via the UI (file picker, or via CLI:
//   ./co2-runner run journeys/example.spec.js

import { expect, test } from "@playwright/test";

test("Branch Magazine reader journey", async ({ page }) => {
  await page.goto("https://branch.climateaction.tech/", {
    waitUntil: "networkidle",
  });
  // Human-like scroll
  await page.mouse.wheel(0, 600);
  await page.waitForTimeout(3000);
  await page.getByRole("link", { name: "Go to issue 9" }).click();
  await page.waitForLoadState("domcontentloaded");
  await page.mouse.wheel(0, 800);
  await page.waitForTimeout(4000);
});
