// runner/run-script.ts — executes a Playwright `codegen`-style .spec.js /
// .spec.ts file under @playwright/test, capturing the Mozilla Profiler
// power data + a HAR archive alongside the existing YAML pipeline's output.
//
// co2-runner supports two journey formats:
//   1. .yaml / .yml — hand-written declarative journeys (runner/run.ts)
//   2. .js / .mjs / .ts — Playwright codegen scripts (this file)
//
// HAR capture: we generate a playwright.config.ts sibling that uses
// `use.contextOptions.recordHar` to embed a full HAR (with response
// bodies) for every test in the file, written to <artefacts-dir>/<slug>.har.
//
// Energy capture: we set MOZ_PROFILER_* env vars on the test subprocess;
// Playwright's browser launcher inherits them and Firefox writes its
// profile to <artefacts-dir>/<slug>-profile.json on shutdown. The existing
// parseEnergyProfile() sums the power counters.

import { extname } from "path";
import { parseEnergyProfile } from "./energy.ts";
import { artefactsDir } from "../ui/paths.ts";
import { DenoNotFoundError, findDenoBinary } from "../util/deno-bin.ts";
import type { ResultsStore } from "../ui/results.ts";
import type { JourneyResult } from "../types.ts";

const slugify = (s: string) =>
  s.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "") || "journey";

/** Extensions we treat as Playwright codegen scripts (vs YAML journeys). */
export const SCRIPT_EXTENSIONS = [".js", ".mjs", ".ts", ".spec.js", ".spec.ts"];

export function isScriptFile(path: string): boolean {
  const lower = path.toLowerCase();
  // Handle compound suffixes like `example.spec.js` first.
  if (lower.endsWith(".spec.js") || lower.endsWith(".spec.ts")) return true;
  const ext = extname(lower);
  return ext === ".js" || ext === ".mjs" || ext === ".ts";
}

/**
 * Runs `playwright test --list` against the script, returns the number of
 * test() registrations found. Used for single-test validation: we reject
 * files with more than one test() (codegen output is single-test by default;
 * multi-test files fragment energy data across browser sessions).
 *
 * Returns 0 if Playwright can't parse the file (syntax error, etc.) — the
 * caller surfaces that as a journey-failure error.
 */
export async function countTests(
  scriptPath: string,
  configPath: string,
): Promise<number> {
  // Resolve the deno CLI binary; throws DenoNotFoundError if absent.
  const denoBin = await findDenoBinary();
  if (!denoBin) throw new DenoNotFoundError();

  // cwd = artefacts dir (the parent of the generated playwright.config.ts).
  // Not strictly necessary for `--list` (which doesn't run tests), but
  // keeps the spawn contract uniform with the actual test-run spawn below.
  const cmd = new Deno.Command(denoBin, {
    cwd: artefactsDir(),
    args: [
      "run",
      "-A",
      "--allow-scripts=npm:playwright",
      "npm:@playwright/test",
      "test",
      "--list",
      "--config",
      configPath,
    ],
    stdout: "piped",
    stderr: "piped",
  });
  const child = cmd.spawn();
  const [status, stdout, stderr] = await Promise.all([
    child.status,
    readAll(child.stdout),
    readAll(child.stderr),
  ]);

  if (!status.success) {
    // Test discovery itself errored — surface the message.
    const msg = stderr || stdout ||
      `playwright test --list exited ${status.code}`;
    throw new Error(`failed to list tests in ${scriptPath}: ${msg}`);
  }

  // Output lines look like:
  //   "  ../private/tmp/example.spec.js:3:5 › test"
  //   "Total: 1 test in 1 file"
  const match = stdout.match(/Total:\s+(\d+)\s+test/);
  if (!match) return 0;
  return parseInt(match[1], 10);
}

async function readAll(stream: ReadableStream<Uint8Array>): Promise<string> {
  const reader = stream.getReader();
  const dec = new TextDecoder();
  let buf = "";
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buf += dec.decode(value, { stream: true });
  }
  return buf;
}

/**
 * Generate a playwright.config.ts that:
 *  - Points at the user's script via testDir/testMatch
 *  - Captures a full HAR via use.contextOptions.recordHar
 *  - Configures Firefox as the browser (the test launcher picks this up via
 *    the --browser=firefox CLI flag we pass; we also set it in config so
 *    `--list` doesn't try to use the default chromium)
 */
function buildPlaywrightConfig(opts: {
  scriptPath: string; // absolute
  harPath: string; // absolute
  slowMo?: boolean;
  filmReel?: boolean;
}): string {
  const { scriptPath, harPath, slowMo, filmReel } = opts;
  // testDir is the parent of the script; testMatch is the script basename.
  const scriptDir = scriptPath.substring(0, scriptPath.lastIndexOf("/"));
  const scriptName = scriptPath.substring(scriptPath.lastIndexOf("/") + 1);

  return `// Auto-generated by co2-runner. Do not edit.
// Generated config that wires HAR capture + Firefox selection + headed
// mode into a user's codegen script. Deleted after the journey completes.
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: ${JSON.stringify(scriptDir)},
  testMatch: ${JSON.stringify(scriptName)},
  use: {
    browserName: "firefox",
    // Headed mode — matches the YAML pipeline's behaviour. Headless mode
    // changes the power profile significantly + makes measurements less
    // meaningful (and is confusing UX: the user clicks Run and sees
    // nothing happen until the energy figure appears).
    headless: false,
    ${slowMo ? "slowMo: 1500," : "// slowMo disabled"}
    ${
    filmReel
      ? 'firefoxUserPrefs: { "gfx.webrender.all": false, "layers.acceleration.force-enabled": false, "gfx.webrender.enabled": false },'
      : "// filmReel disabled"
  }
    contextOptions: {
      recordHar: {
        path: ${JSON.stringify(harPath)},
        mode: "full",
        content: "embed",
      },
    },
  },
  projects: [
    { name: "firefox", use: { ...devices["Desktop Firefox"] } },
  ],
});
`;
}

/**
 * Executes a Playwright codegen script and collects energy + HAR artefacts.
 *
 * Throws if the script contains more than one test() (code-generated
 * journeys should be single-test; multi-test runs fragment energy data).
 * Throws on assertion failure (Playwright exits non-zero) — the caller
 * surfaces the failure message via an SSE 'progress' error event.
 */
export async function runScript(
  scriptPath: string,
  store?: ResultsStore,
  opts?: { displayName?: string; slowMo?: boolean; filmReel?: boolean },
): Promise<JourneyResult> {
  const ARTEFACTS_DIR = artefactsDir();
  await Deno.mkdir(ARTEFACTS_DIR, { recursive: true });

  // Resolve to an absolute path. Playwright resolves testDir relative to
  // the config file's location (which lives in ARTEFACTS_DIR, NOT the
  // caller's cwd), so relative script paths break otherwise.
  const absScriptPath = await Deno.realPath(scriptPath);

  // Derive a display name + slug from the script's basename (minus extension).
  // The caller can override the display name (e.g. when the temp file has a
  // prefix that shouldn't appear in the result). Falls back to the basename.
  const basename = absScriptPath.substring(absScriptPath.lastIndexOf("/") + 1);
  const name = opts?.displayName ??
    (basename.replace(/\.(spec\.)?(js|mjs|ts)$/i, "") || "journey");
  const slug = slugify(name);

  const PROFILE_PATH = `${ARTEFACTS_DIR}/${slug}-profile.json`;
  const HAR_PATH = `${ARTEFACTS_DIR}/${slug}.har`;
  const CONFIG_PATH = `${ARTEFACTS_DIR}/${slug}-playwright.config.ts`;

  const configContents = buildPlaywrightConfig({
    scriptPath: absScriptPath,
    harPath: HAR_PATH,
    slowMo: opts?.slowMo,
    filmReel: opts?.filmReel,
  });
  await Deno.writeTextFile(CONFIG_PATH, configContents);

  try {
    // ── Validate: single test only ────────────────────────────────────────
    store?.progress({
      name,
      stepIndex: -1,
      totalSteps: 0,
      action: "validate",
      status: "running",
      message: "checking script has exactly one test()...",
    });
    const testCount = await countTests(absScriptPath, CONFIG_PATH);
    if (testCount === 0) {
      throw new Error(
        `no test() registrations found in ${basename} — expected exactly 1`,
      );
    }
    if (testCount > 1) {
      throw new Error(
        `${basename} has ${testCount} test() registrations — co2-runner only supports single-test scripts. ` +
          `Please split the journey into one test per file (codegen output is single-test by default).`,
      );
    }

    // ── Spawn `playwright test` ───────────────────────────────────────────
    store?.progress({
      name,
      stepIndex: 0,
      totalSteps: 1,
      action: "run",
      status: "running",
      message: "launching Firefox + running journey script...",
    });

    const denoBin = await findDenoBinary();
    if (!denoBin) throw new DenoNotFoundError();

    // Run the subprocess with cwd = ARTEFACTS_DIR. Without this, the
    // subprocess inherits the parent's cwd, which when the desktop app
    // is launched via Finder is `/` (read-only on modern macOS).
    // @playwright/test tries to mkdir `test-results/` in its cwd and
    // crashes with `EROFS: read-only file system, mkdir '/test-results/...'`.
    // The artefacts dir is one we own + create, so it's always writable.
    const cmd = new Deno.Command(denoBin, {
      cwd: ARTEFACTS_DIR,
      args: [
        "run",
        "-A",
        "--allow-scripts=npm:playwright",
        "npm:@playwright/test",
        "test",
        "--config",
        CONFIG_PATH,
        "--reporter=line",
      ],
      env: {
        ...Deno.env.toObject(),
        MOZ_PROFILER_STARTUP: "1",
        MOZ_PROFILER_STARTUP_ENTRIES: "10000000",
        MOZ_PROFILER_STARTUP_INTERVAL: "10",
        MOZ_PROFILER_STARTUP_FEATURES: opts?.filmReel
          ? "js,stackwalk,cpu,screenshots,power"
          : "js,stackwalk,cpu,power",
        MOZ_PROFILER_STARTUP_THREADS: "GeckoMain,Compositor,Renderer",
        MOZ_PROFILER_STARTUP_FILTERS: "GeckoMain,Compositor,Renderer",
        MOZ_PROFILER_SHUTDOWN: PROFILE_PATH,
      },
      stdout: "piped",
      stderr: "piped",
    });
    const child = cmd.spawn();

    // Forward stdout (test runner output) to the server console AND capture
    // it so we can include it in the SSE error event if the journey fails.
    const dec = new TextDecoder();
    let stdoutBuf = "";
    let stderrBuf = "";
    const readStream = async (
      stream: ReadableStream<Uint8Array>,
      sink: (s: string) => void,
    ) => {
      const reader = stream.getReader();
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        const text = dec.decode(value, { stream: true });
        sink(text);
      }
    };
    await Promise.all([
      readStream(child.stdout, (s) => {
        stdoutBuf += s;
        console.log(s.trimEnd());
      }),
      readStream(child.stderr, (s) => {
        stderrBuf += s;
        console.error(s.trimEnd());
      }),
    ]);

    const status = await child.status;

    if (!status.success) {
      // Include the actual playwright error output so the UI sees something
      // actionable, not just "exit code 1 — see server stderr" (the server
      // stderr isn't visible to the user in the desktop app).
      const failureOutput = (stderrBuf || stdoutBuf).trim().slice(-800);
      throw new Error(
        `journey script failed (exit code ${status.code}):\n${failureOutput}`,
      );
    }

    // ── Parse energy + return ─────────────────────────────────────────────
    const result = await parseEnergyProfile(PROFILE_PATH, name);
    store?.push(result);
    return result;
  } finally {
    // Clean up the generated playwright.config.ts (artefacts like the
    // profile + HAR stay — those are the user's deliverables).
    await Deno.remove(CONFIG_PATH).catch(() => {});
  }
}
